In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("./data/nutrition.csv")
df.shape

(198, 6)

In [4]:
df[['user_input']].head()

                                          user_input
0                              체중에 대한 잘못된 정보는 무엇인가요?
1                  수유에 대해 아기가 스스로 먹게 하려면 어떻게 해야 하나요?
2       낙농업체와 관련된 우유의 안전성에 대한 소아청소년과 전문의의 의견은 무엇인가요?
3                   아이에게 멸균우유를 먹이는 것이 적절한 상황은 무엇인가요?
4  비만과 관련하여 아이가 잘 먹지 않는 경우, 부모가 가장 먼저 확인해야 할 사항은 ...

In [8]:
df['is_true'] = df['user_input'].map(lambda x: True if "오트밀" in x else False)

In [10]:
df[df['is_true'] == True]

,user_input,reference,reference_video_url,persona_name,query_style,query_length,is_true
9,아기에게 오트밀을 어떻게 먹일 수 있나요?,"오트밀은 사과나 바나나, 아보카도와 섞어주면 아기가 맛있게 먹을 수 있습니다.",https://www.youtube.com/watch?v=XP4Y8nNvdDA,a pediatrician,PERFECT_GRAMMAR,SHORT,True
44,오트밀은 아기에게 언제부터 주면 좋나요?,오트밀은 알레르기를 잘 일으키지 않으므로 이유식 초기부터 쌀죽과 함께 동시에 시작해...,https://www.youtube.com/watch?v=J43GQGMKCCQ,a pediatrician,MISSPELLED,SHORT,True
50,퀵 오트밀은 이유식에 어떻게 사용되나요?,"오트밀은 이유식 재료로 사용할 수 있으며, 초기에는 퀵 오트밀(입자가 곱고 퍼지는 ...",https://www.youtube.com/watch?v=rRFmPPSZILA,a pediatric nutrition expert,MISSPELLED,MEDIUM,True
127,오트밀은 아기 이유식에 어떻게 좋나요?,오트밀은 이유식을 하면서 수유량이 줄어든 아기에게 좋습니다. 이유식의 구성이나 양을...,https://www.youtube.com/watch?v=0J6dh_a0I9I,a child nutrition specialist,POOR_GRAMMAR,MEDIUM,True
131,어린이에게 오트밀을 주는 것이 왜 중요한가요?,"이유식 시에는 오트밀이나 보리, 쌀, 현미 같은 곡류와 채소, 과일을 골고루 주면 ...",https://www.youtube.com/watch?v=YKp7ta1H0c0,a child nutrition specialist,PERFECT_GRAMMAR,SHORT,True
140,퀵 오트밀은 아기 이유식에 어떻게 사용되나요?,"오트밀은 이유식 재료로 사용할 수 있으며, 초기에는 퀵 오트밀(입자가 곱고 퍼지는 ...",https://www.youtube.com/watch?v=rRFmPPSZILA,a child nutrition specialist,MISSPELLED,MEDIUM,True
197,오트밀은 아기 이유식에 어떤 역할을 하나요?,오트밀은 아기 이유식에서 쌀과 섞어 사용하거나 대안으로 시작하는 것이 권장됩니다. ...,https://www.youtube.com/watch?v=mYABC4UAeEU,a pediatric nutrition expert,MISSPELLED,MEDIUM,True

In [17]:
df[df['user_input'] == "부모가 아이의 식습관을 개선하기 위해 어떤 규칙을 세워야 하나요?"]['reference'].values[0]

'부모는 식사 시간이 지나면 음식을 치우고, 아이가 배가 고프면 결국 먹게 된다는 것을 가르쳐야 합니다. 식사 시간과 간식 시간 외에는 반드시 부모의 허락을 받고 먹는다는 규칙을 정해 일관되게 지켜야 하며, 간식은 평소 주는 양만 주되 더 달라고 해도 더 주지 않아야 합니다.'